// Re-export from packages/auth for use in the Next.js app via @/lib/auth
// This bridges the monorepo package to the app's import system

export {
  generateAccessToken,
  generateRefreshToken,
  generateTokenPair,
  verifyAccessToken,
  verifyRefreshToken,
  extractBearerToken,
  getAccessTokenExpiry,
  type TokenPayload,
  type TokenPair,
  type TokenUser,
  createSession,
  getSession,
  updateSessionActivity,
  deleteSession,
  deleteAllUserSessions,
  getUserActiveSessions,
  disconnectRedis,
  getRedis,
  type SessionData,
  type SessionInfo,
  hashPassword,
  verifyPassword,
  validatePassword,
  getPasswordStrength,
  passwordSchema,
  type PasswordValidationResult,
  type PasswordStrength,
  getGoogleAuthUrl,
  getGoogleUser,
  refreshGoogleToken,
  type GoogleUser,
  // OTP Authentication
  type OTPChannel,
  type OTPPurpose,
  type OTPRequest,
  type OTPVerification,
  type OTPResult,
  type OTPConfig,
  DEFAULT_OTP_CONFIG,
  generateOTP,
  storeOTP,
  verifyOTP,
  isOnCooldown,
  getCooldownRemaining,
  blockDestination,
  isBlocked,
  clearOTP,
  getWhatsAppProvider,
  getSMSProvider,
  sendEmailOTP,
} from '../../packages/auth/src';
